<?php

namespace ContainerMPfnHrT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KMceHmkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kMceHmk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kMceHmk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Badge' => ['privates', '.errored..service_locator.kMceHmk.App\\Entity\\Badge', NULL, 'Cannot autowire service ".service_locator.kMceHmk": it references class "App\\Entity\\Badge" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'Badge' => 'App\\Entity\\Badge',
            'entityManager' => '?',
        ]);
    }
}
