<?php

namespace ContainerMPfnHrT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._p8DWNA.App\Entity\Certificat' shared service.
     *
     * @return \App\Entity\Certificat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._p8DWNA": it references class "App\\Entity\\Certificat" but no such service exists.');
    }
}
