<?php

namespace ContainerTrlYqFT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_86Icc1PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.86Icc1P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.86Icc1P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BadgeController::delete' => ['privates', '.service_locator._gQqk7e', 'get_ServiceLocator_GQqk7eService', true],
            'App\\Controller\\BadgeController::edit' => ['privates', '.service_locator.kMceHmk', 'get_ServiceLocator_KMceHmkService', true],
            'App\\Controller\\BadgeController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CertificatController::delete' => ['privates', '.service_locator.g.BzHP_', 'get_ServiceLocator_G_BzHPService', true],
            'App\\Controller\\CertificatController::edit' => ['privates', '.service_locator.iDbffAb', 'get_ServiceLocator_IDbffAbService', true],
            'App\\Controller\\CertificatController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CertificatController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CertificatController::show' => ['privates', '.service_locator._p8DWNA', 'get_ServiceLocator_P8DWNAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\BadgeController:delete' => ['privates', '.service_locator._gQqk7e', 'get_ServiceLocator_GQqk7eService', true],
            'App\\Controller\\BadgeController:edit' => ['privates', '.service_locator.kMceHmk', 'get_ServiceLocator_KMceHmkService', true],
            'App\\Controller\\BadgeController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CertificatController:delete' => ['privates', '.service_locator.g.BzHP_', 'get_ServiceLocator_G_BzHPService', true],
            'App\\Controller\\CertificatController:edit' => ['privates', '.service_locator.iDbffAb', 'get_ServiceLocator_IDbffAbService', true],
            'App\\Controller\\CertificatController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CertificatController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CertificatController:show' => ['privates', '.service_locator._p8DWNA', 'get_ServiceLocator_P8DWNAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\BadgeController::delete' => '?',
            'App\\Controller\\BadgeController::edit' => '?',
            'App\\Controller\\BadgeController::index' => '?',
            'App\\Controller\\CertificatController::delete' => '?',
            'App\\Controller\\CertificatController::edit' => '?',
            'App\\Controller\\CertificatController::index' => '?',
            'App\\Controller\\CertificatController::new' => '?',
            'App\\Controller\\CertificatController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BadgeController:delete' => '?',
            'App\\Controller\\BadgeController:edit' => '?',
            'App\\Controller\\BadgeController:index' => '?',
            'App\\Controller\\CertificatController:delete' => '?',
            'App\\Controller\\CertificatController:edit' => '?',
            'App\\Controller\\CertificatController:index' => '?',
            'App\\Controller\\CertificatController:new' => '?',
            'App\\Controller\\CertificatController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
