<?php

namespace ContainerTrlYqFT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P8DWNAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._p8DWNA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._p8DWNA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'certificat' => ['privates', '.errored..service_locator._p8DWNA.App\\Entity\\Certificat', NULL, 'Cannot autowire service ".service_locator._p8DWNA": it references class "App\\Entity\\Certificat" but no such service exists.'],
        ], [
            'certificat' => 'App\\Entity\\Certificat',
        ]);
    }
}
