index:
  path: /test
  controller: App\Controller\TestController::index

login:
  path: /login
  controller: App\Controller\LoginController::login

app_list_formations:
  path: /formations
  controller: 'App\Controller\FormationController::listFormations'
  methods: GET

app_back:
  path: /Back
  controller: 'App\Controller\BackController::index'
  methods: GET

app_front:
  path: /Front
  controller: 'App\Controller\FrontController::index'
  methods: GET
courses:
  path: "/courses"
  controller: App\Controller\FormationController::courses
  
app_user_form_room_delete_client:
    path: '/user/form/room/{idFR}/delete/client/{userId}'
    controller: 'App\Controller\UserFormRoomController::deleteClient'
    methods: ['POST']
    
app_formation_new1:
    path: /newformation
    controller: App\Controller\FormationController::newFormation
    methods: ['GET', 'POST']

app_client_formations:
    path: /user/formations
    controller: App\Controller\UserFormRoomController::getUserFormations
    methods: ['GET']
app_user_form_room_calendar:
    path: '/user/form/room/calendar'
    controller: 'App\Controller\UserFormRoomController::calendar'
    methods: ['GET']
app_formateur_formations:
    path: /formateur/formations
    controller: App\Controller\UserFormRoomController::getFormateurFormations
    methods: ['GET']
