# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory: '%kernel.project_dir%/public/uploads'

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
      


    # Define your custom QR code builder service
    App\Service\CustomQrCodeBuilder:
        class: App\Service\CustomQrCodeBuilder
    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones
    Endroid\QrCode\QrCode:
        class: Endroid\QrCode\QrCode 
knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf"'
        options: []
    image:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage"'
        options: []



vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '%images_directory%'
            upload_destination: '%kernel.project_dir%/public%images_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true

