<?php

namespace ContainerPVcAg4x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGnxDP3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TGnxDP3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TGnxDP3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'usrEvt' => ['privates', '.errored..service_locator.TGnxDP3.App\\Entity\\UsrEvt', NULL, 'Cannot autowire service ".service_locator.TGnxDP3": it references class "App\\Entity\\UsrEvt" but no such service exists.'],
        ], [
            'usrEvt' => 'App\\Entity\\UsrEvt',
        ]);
    }
}
