<?php

namespace ContainerPVcAg4x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KWgPKLQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kWgPKLQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kWgPKLQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EvenementController::delete' => ['privates', '.service_locator.wXSRjZL', 'get_ServiceLocator_WXSRjZLService', true],
            'App\\Controller\\EvenementController::edit' => ['privates', '.service_locator.wXSRjZL', 'get_ServiceLocator_WXSRjZLService', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EvenementController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EvenementController::search' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EvenementController::show' => ['privates', '.service_locator.yAvMNdP', 'get_ServiceLocator_YAvMNdPService', true],
            'App\\Controller\\EvenementCsvController::exportEvenementsCsv' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\TestController::events' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\TestController::eventsingle' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UsrEvtController::delete' => ['privates', '.service_locator.ndG5AvI', 'get_ServiceLocator_NdG5AvIService', true],
            'App\\Controller\\UsrEvtController::edit' => ['privates', '.service_locator.ndG5AvI', 'get_ServiceLocator_NdG5AvIService', true],
            'App\\Controller\\UsrEvtController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UsrEvtController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UsrEvtController::show' => ['privates', '.service_locator.TGnxDP3', 'get_ServiceLocator_TGnxDP3Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\EvenementController:delete' => ['privates', '.service_locator.wXSRjZL', 'get_ServiceLocator_WXSRjZLService', true],
            'App\\Controller\\EvenementController:edit' => ['privates', '.service_locator.wXSRjZL', 'get_ServiceLocator_WXSRjZLService', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EvenementController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EvenementController:search' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EvenementController:show' => ['privates', '.service_locator.yAvMNdP', 'get_ServiceLocator_YAvMNdPService', true],
            'App\\Controller\\EvenementCsvController:exportEvenementsCsv' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\TestController:events' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\TestController:eventsingle' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UsrEvtController:delete' => ['privates', '.service_locator.ndG5AvI', 'get_ServiceLocator_NdG5AvIService', true],
            'App\\Controller\\UsrEvtController:edit' => ['privates', '.service_locator.ndG5AvI', 'get_ServiceLocator_NdG5AvIService', true],
            'App\\Controller\\UsrEvtController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UsrEvtController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UsrEvtController:show' => ['privates', '.service_locator.TGnxDP3', 'get_ServiceLocator_TGnxDP3Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\EvenementController::delete' => '?',
            'App\\Controller\\EvenementController::edit' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::new' => '?',
            'App\\Controller\\EvenementController::search' => '?',
            'App\\Controller\\EvenementController::show' => '?',
            'App\\Controller\\EvenementCsvController::exportEvenementsCsv' => '?',
            'App\\Controller\\TestController::events' => '?',
            'App\\Controller\\TestController::eventsingle' => '?',
            'App\\Controller\\UsrEvtController::delete' => '?',
            'App\\Controller\\UsrEvtController::edit' => '?',
            'App\\Controller\\UsrEvtController::index' => '?',
            'App\\Controller\\UsrEvtController::new' => '?',
            'App\\Controller\\UsrEvtController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EvenementController:delete' => '?',
            'App\\Controller\\EvenementController:edit' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:new' => '?',
            'App\\Controller\\EvenementController:search' => '?',
            'App\\Controller\\EvenementController:show' => '?',
            'App\\Controller\\EvenementCsvController:exportEvenementsCsv' => '?',
            'App\\Controller\\TestController:events' => '?',
            'App\\Controller\\TestController:eventsingle' => '?',
            'App\\Controller\\UsrEvtController:delete' => '?',
            'App\\Controller\\UsrEvtController:edit' => '?',
            'App\\Controller\\UsrEvtController:index' => '?',
            'App\\Controller\\UsrEvtController:new' => '?',
            'App\\Controller\\UsrEvtController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
