<?php

namespace ContainerPVcAg4x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NdG5AvIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ndG5AvI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ndG5AvI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'usrEvt' => ['privates', '.errored..service_locator.ndG5AvI.App\\Entity\\UsrEvt', NULL, 'Cannot autowire service ".service_locator.ndG5AvI": it references class "App\\Entity\\UsrEvt" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'usrEvt' => 'App\\Entity\\UsrEvt',
        ]);
    }
}
