<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMPfnHrT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMPfnHrT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMPfnHrT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMPfnHrT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMPfnHrT\App_KernelDevDebugContainer([
    'container.build_hash' => 'MPfnHrT',
    'container.build_id' => 'bf9ae0f9',
    'container.build_time' => 1713503413,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMPfnHrT');
