<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1bKZEhF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1bKZEhF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1bKZEhF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1bKZEhF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1bKZEhF\App_KernelDevDebugContainer([
    'container.build_hash' => '1bKZEhF',
    'container.build_id' => '71e07c40',
    'container.build_time' => 1714653470,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1bKZEhF');
