<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPVcAg4x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPVcAg4x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPVcAg4x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPVcAg4x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPVcAg4x\App_KernelDevDebugContainer([
    'container.build_hash' => 'PVcAg4x',
    'container.build_id' => 'f92243e3',
    'container.build_time' => 1714091477,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPVcAg4x');
